platform :ios, '9.0'

target 'LiuMeiTuanIpad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiuMeiTuanIpad

  pod 'YYModel', '~> 1.0.4'
  pod 'Masonry', '~> 1.0.2'

end
